set hlsearch
set incsearch
set ignorecase
set smartcase
set wildmenu
set wildmode=list:longest,full
set wildignore=*.o,.DS_Store
set backspace=2
set whichwrap+=<,>,h,l,[,]
set shortmess=filtIoOA
set report=0
set nostartofline
set gdefault
